<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>fd4ce38d-3b3c-4ea9-ba12-b1639caa1deb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CS-Script" Version="4.14.11" />
    <PackageReference Include="HiveMQtt" Version="0.45.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IMessageTransformer\IMessageTransformer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Transforms\Broken.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Transforms\BrokenTopic.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Transforms\Lower.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Transforms\LowerUpper.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Transforms\ReturnsNull.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Transforms\ReturnsNullMessage.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Transforms\ReturnsOneNullMessageMiddle.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Transforms\ReturnsOneNullMessageStart.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Transforms\ReturnsOneNullMessageEnd.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Transforms\Upper.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Using Include="CSScriptLib" />
    <Using Include="Microsoft.Extensions.Caching.Memory" />
    <Using Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

</Project>
