<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>52a24b3b-955e-4b63-b9a5-7a6e6488ef24</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CS-Script" Version="4.13.2" />
    <PackageReference Include="HiveMQtt" Version="0.39.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Transforms\resumed.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Transforms\stopped.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Using Include=" HiveMQtt.MQTT5.Types" />
    <Using Include="HiveMQtt.Client" />
    <Using Include="HiveMQtt.MQTT5.ReasonCodes" />
    <Using Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

</Project>
