<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8794e472-4170-4a61-a1fa-ec6a14f27711</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CS-Script" Version="4.13.1" />
    <PackageReference Include="HiveMQtt" Version="0.37.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

</Project>
